### PR TITLE
README: Add bundler as dependency

### PR DESCRIPTION
**Pull request by blabber**
Starting with 6fdf25f6ac70223e45c544bb497a3c5e6e4e642e this project depends on
`bundler`. Document this dependency in the README.md.

CAVEAT: As I am using FreeBSD I am not totally sure that the Debian package is
really called `bundler` although packages.debian.org suggests that my edit is
correct.

### CODE REVIEW

**Comment by else** [comment]
Well in that case we should also document how to install jekyll locally instead of globally.

**Comment by blabber** [comment]
I don't know how to do this as I installed jekyll globally. But calling `grunt` fails without installed bundler.

**Comment by else** [comment]
see https://github.com/raumzeitlabor/rzl-homepage/blob/master/.travis.yml#L5

**Comment by blabber** [comment]
I suppose `$PATH` has to be adapted as well? I will take a look at this tomorrow.

**Comment by else** [comment]
No, because of https://github.com/raumzeitlabor/rzl-homepage/blob/master/Gruntfile.js#L457 bundler should handle that just fine. Actually it looks it already does with a globally installed jekyll?

**Comment by blabber** [comment]
I did a clean room installation and documented my steps to get this running with locally installed jekyll. I will massage this into a update to this PR this evening.

**Comment by else** [comment]
:+1:

**Pull request merged**
