### PR TITLE
Fix gallery rendering

### LINKED ISSUE #5: Tumblr image gallery breaks on small page widths and / or resizes
It seems that the justified image gallery we use to display our Tumblr posts has problems with smaller resolutions and / or resizes.

### PR DESCRIPTION
**Pull request by else**
Correct racy code segments and use more tolerant targeted height
resizing.

closes #5, #35

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/raumzeitlabor/rzl-homepage/pull/168" target="_blank">ReviewNinja

**Comment by else** [comment]
WTF is this shit?

https://travis-ci.org/raumzeitlabor/rzl-homepage/builds/67771145

**Comment by else** [comment]
https://github.com/npm/npm/issues/8631

**Comment by lutoma** [comment]
:+1:

**Pull request merged**
