### PR TITLE
DON'T MERGE: Delete unused files

### LINKED ISSUE #115: Purge unreferenced image files
[Here](https://github.com/abrock/Katzenfutter/blob/master/rzl-homepage/orphans2-full-path.txt) is a list of file not referenced by any file in the repository, found by [this script](https://stackoverflow.com/questions/8161259/how-do-i-make-a-bash-script-to-find-unused-images-in-a-project#8174681) and cross-checked against a complete download of raumzeitlabor.de.

A lot of files are scaled versions of large images used by Wordpress but not used by the current setup. Purging these from the repo history would free roughly 95,448,311 bytes.

The list still needs work, as there are false positives in the list, e.g. else.png which is [definitely used](https://raumzeitlabor.de/blog/projekt-solar-powered-router/) but only referenced via something I didn't trace down yet (CSS|JS?). It might be safe to purge every listed file within assets/uploads but I can't guarantee that atm.

### PR DESCRIPTION
**Pull request by else**
These files are included in our repository but referenced nowhere.

*Please don't merge this pull request, it is created only for previewing the change on http://pr-116.rzl-homepage.raumzeitlabor.org.*

It is probably a good idea to run the [unused-images](https://github.com/raumzeitlabor/rzl-homepage/issues/115#issue-63851166) script again.

closes #115

### CODE REVIEW

**Comment by abrock** [comment]
The linkchecker doesn't find any missing images in the preview except for /assets/power_cell.png in http://pr-116.rzl-homepage.raumzeitlabor.org/blog/projekt-solar-powered-router/ which was already missing before, so I think it should be safe to force-push the change.

**Comment by else** [comment]
Thanks, will do later.

**Comment by else** [comment]
So, I just tried this using [bfg](https://rtyley.github.io/bfg-repo-cleaner/). Here's what I did:

1. git clone --bare
2. du -sh: 262 MB
3. run bfg
4. expire reflog and trigger git gc
5. du -sh: 259 MB

Unsure why we only save 3 MB. Also, bfg only supports deleting by filename (without path). Some of the files in app/assets/upload are located under app/assets and are actually used, so we should be careful here.

**Comment by abrock** [comment]
I managed to shrink it to 175MB: https://github.com/abrock/rzl-homepage

I took my local (slightly outdated) version where the latest commit is "Add missing image files...", then compressed all the png files using optipng -o7 and deleted every orphaned file.
Then I ran bfg etc.

**Pull request closed without merging**
